version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.1
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      http.cors.enabled: "true"
      http.cors.allow-origin: "/.*/"
      http.cors.allow-headers: "X-Requested-With,Content-Length,Content-Type,Authorization"
      TAKE_FILE_OWNERSHIP: 1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/elasticsearch:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.7.1
    depends_on:
      - elasticsearch
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  ldap:
    image: dcm4che/slapd-dcm4chee:2.4.44-17.0
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/ldap:/var/lib/ldap
      - /var/local/dcm4chee-arc/slapd.d:/etc/ldap/slapd.d
  keycloak:
    image: dcm4che/keycloak:6.0.1-17.0
    ports:
      - "8880:8880"
      - "8843:8843"
      - "8990:8990"
      - "8993:8993"
    environment:
      HTTP_PORT: 8880
      HTTPS_PORT: 8843
      MANAGEMENT_HTTP_PORT: 8990
      MANAGEMENT_HTTPS_PORT: 8993
      KEYCLOAK_WAIT_FOR: ldap:389
    depends_on:
      - ldap
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/keycloak:/opt/keycloak/standalone
  keycloak-gatekeeper:
    image: dcm4che/keycloak-gatekeeper:6.0.1-update-ca-certificates
    ports:
      - "8643:8643"
    volumes:
      - ./certs/cacert.pem:/usr/local/share/ca-certificates/IHE-Europe-CA.crt
    environment:
      UPDATE_CA_CERTIFICATES: 1
      PROXY_LISTEN: :8643
      PROXY_REDIRECTION_URL: https://gunter-nb:8643
      PROXY_UPSTREAM_URL: http://kibana:5601
      PROXY_DISCOVERY_URL: https://PACS_J4C:8843/auth/realms/dcm4che
      PROXY_CLIENT_ID: kibana
      PROXY_CLIENT_SECRET: 5c7d81c4-875d-4905-93ba-9abad7c4c6ee
      PROXY_ENCRYPTION_KEY: AgXa7xRcoClDEU0ZDSH4X0XhL5Qy2Z2j
    command:
      - "--openid-provider-timeout=120s"
      - "--tls-cert=/etc/certs/cert.pem"
      - "--tls-private-key=/etc/certs/key.pem"
      - "--skip-openid-provider-tls-verify=false"
      - "--enable-refresh-tokens=true"
      - "--enable-token-header=false"
      - "--enable-authorization-header=false"
      - "--enable-authorization-cookies=false"
      - "--resources=uri=/*|roles=auditlog"
    extra_hosts:
      - PACS_J4C:192.168.2.131
    depends_on:
      - kibana
      - keycloak
